import { expect, test, type Page } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const evidence = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../docs/assets/logistics')
fs.mkdirSync(evidence, { recursive: true })
const nav = (page: Page, name: string) => page.locator(`[data-test="nav-${name}"]`)

async function enter(page: Page, username = 'logistics') {
  await page.goto('logistics')
  await page.getByLabel('用户名', { exact: true }).fill(username)
  await page.getByLabel('密码', { exact: true }).fill('Logistics!2026')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/\/app\/logistics$/)
  await expect(page.getByRole('heading', { name: '物流协同工作台' })).toBeVisible()
  await expect(page.locator('.metrics-grid')).toBeVisible()
}

function beijingInput(date: Date) {
  return new Date(date.getTime() + 8 * 3_600_000).toISOString().slice(0, 19)
}

test('live workbench, grounded patrol, exception resolution and mobile layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await enter(page)
  await page.screenshot({ path: path.join(evidence, 'desktop-overview.png'), fullPage: true })
  const patrol = page.waitForResponse(response => response.url().endsWith('/agent/patrol') && response.request().method() === 'POST')
  await page.locator('[data-test="patrol-button"]').click()
  expect((await patrol).status()).toBe(200)
  await nav(page, 'agent').click()
  const brief = page.waitForResponse(response => response.url().includes('/agent/brief'))
  await page.getByRole('button', { name: '生成今日简报' }).click()
  expect((await brief).status()).toBe(200)
  await expect(page.locator('.message.agent')).toContainText('待发货')
  await expect(page.locator('.citations button').first()).toBeVisible()
  await page.screenshot({ path: path.join(evidence, 'agent-evidence.png'), fullPage: true })
  await nav(page, 'exceptions').click()
  const card = page.locator('.exception-card').filter({ has: page.getByRole('button', { name: '分配工单', exact: true }) }).first()
  await card.getByRole('button', { name: '分配工单', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '处理异常工单' })
  await dialog.getByLabel('选择处理人', { exact: true }).press('ArrowDown')
  await page.getByRole('option', { name: 'logistics', exact: true }).click()
  const assigned = page.waitForResponse(response => response.url().includes('/exceptions/') && response.request().method() === 'PATCH')
  await dialog.getByRole('button', { name: '保存处理结果' }).click()
  expect((await assigned).status()).toBe(200)
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: '处理工单', exact: true }).first().click()
  await dialog.getByLabel('解决说明').fill('已核对仓库交接记录，责任人继续跟进实际物流节点。')
  const resolved = page.waitForResponse(response => response.url().includes('/exceptions/') && response.request().method() === 'PATCH')
  await dialog.getByRole('button', { name: '保存处理结果' }).click()
  expect((await resolved).status()).toBe(200)
  await expect(dialog).toBeHidden()
  await nav(page, 'overview').click()
  await expect(page.locator('.metrics-grid')).toBeVisible()
  await expect(page.locator('.el-message')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const mobileNavigation = await nav(page, 'shipments').boundingBox()
  expect(mobileNavigation!.x + mobileNavigation!.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: path.join(evidence, 'mobile-overview.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('create shipment, dispatch, return immediately and complete reverse logistics', async ({ page }) => {
  await enter(page)
  await nav(page, 'shipments').click()
  await page.getByRole('button', { name: '新建运单', exact: true }).click()
  const create = page.getByRole('dialog', { name: '新建运单', exact: true })
  await create.getByLabel('选择订单', { exact: true }).click()
  await page.getByRole('option').first().click()
  const tracking = `QA${Date.now()}`
  await create.getByLabel('承运商', { exact: true }).fill('顺丰速运')
  await create.getByLabel('运单号', { exact: true }).fill(tracking)
  await create.getByLabel('目的地', { exact: true }).fill('上海市 · 徐汇区')
  await create.getByLabel('计划发货（北京时间）', { exact: true }).fill(beijingInput(new Date(Date.now() + 3_600_000)))
  await create.getByLabel('预计送达（北京时间）', { exact: true }).fill(beijingInput(new Date(Date.now() + 172_800_000)))
  const created = page.waitForResponse(response => response.url().endsWith('/logistics/shipments') && response.request().method() === 'POST')
  await create.getByRole('button', { name: '创建运单', exact: true }).click()
  const createdResponse = await created
  expect(createdResponse.status()).toBe(201)
  const shipment = await createdResponse.json()
  await expect(create).toBeHidden()
  const drawer = page.getByRole('dialog', { name: '运单详情', exact: true })
  await expect(drawer).toBeVisible()
  await drawer.getByRole('button', { name: '新增物流节点' }).click()
  const event = page.getByRole('dialog', { name: '新增物流节点', exact: true })
  await event.getByLabel('地点', { exact: true }).fill('杭州仓库')
  await event.getByLabel('节点说明', { exact: true }).fill('已完成包装并交接承运商。')
  const dispatched = page.waitForResponse(response => response.url().endsWith('/events') && response.request().method() === 'POST')
  await event.getByRole('button', { name: '保存节点' }).click()
  expect((await dispatched).status()).toBe(200)
  await expect(event).toBeHidden()
  await expect(drawer.locator('.detail-hero')).toContainText('运输中')
  await page.screenshot({ path: path.join(evidence, 'shipment-detail.png'), fullPage: true })
  await drawer.getByRole('button', { name: '发起退货' }).click()
  const returnDialog = page.getByRole('dialog', { name: '发起退货', exact: true })
  await returnDialog.getByLabel('退货原因', { exact: true }).fill('客户申请更换规格，核对退回包裹。')
  const requested = page.waitForResponse(response => response.url().endsWith('/logistics/returns') && response.request().method() === 'POST')
  await returnDialog.getByRole('button', { name: '创建退货任务' }).click()
  expect((await requested).status()).toBe(201)
  await expect(returnDialog).toBeHidden()
  await drawer.getByRole('button', { name: /close|关闭/i }).click()
  await nav(page, 'returns').click()
  await page.getByLabel('搜索退货订单', { exact: true }).fill(shipment.order_number)
  await page.getByRole('button', { name: '筛选', exact: true }).click()
  for (const status of ['approved', 'in_transit', 'received', 'closed']) {
    await page.getByRole('button', { name: '推进处理', exact: true }).click()
    const action = page.getByRole('dialog', { name: '推进退货任务', exact: true })
    if (status === 'in_transit') {
      await action.getByLabel('承运商', { exact: true }).fill('中通快递')
      await action.getByLabel('退回运单号', { exact: true }).fill(`RETURN-${tracking}`)
    }
    await action.getByLabel('处理说明', { exact: true }).fill(status === 'closed' ? '质检完成，外观配件完好，物流结案。' : '已核对本次处理事实。')
    const transitioned = page.waitForResponse(response => response.url().endsWith('/transition') && response.request().method() === 'POST')
    await action.getByRole('button', { name: '确认推进' }).click()
    const result = await transitioned
    expect(result.status(), await result.text()).toBe(200)
    expect((await result.json()).status).toBe(status)
    await expect(action).toBeHidden()
  }
  await expect(page.locator('.el-table__body')).toContainText('已完成')
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出当前页' }).click()
  expect((await downloaded).suggestedFilename()).toMatch(/returns.*\.csv$/)
})

test('real authentication enforces warehouse store scope', async ({ page, request }) => {
  expect((await request.get('/logistics/dashboard')).status()).toBe(401)
  await enter(page, 'warehouse')
  const token = await page.evaluate(() => sessionStorage.getItem('access_token'))
  const headers = { Authorization: `Bearer ${token}` }
  const stores = await (await request.get('/stores', { headers })).json()
  expect(stores).toHaveLength(1)
  const response = await request.get('/logistics/shipments', { headers })
  const result = await response.json()
  expect(result.total).toBeGreaterThan(0)
  expect(result.items.every((item: { store_id: string }) => item.store_id === stores[0].id)).toBe(true)
  expect((await request.get('/logistics/shipments?store_id=unavailable-store', { headers })).status()).toBe(404)
})
